apiVersion: v1
kind: Secret
metadata:
  name: opsledger-secret
  labels:
    app.kubernetes.io/name: opsledger
type: Opaque
stringData:
  db-pass: replace-with-database-password
  rmq-user: replace-with-rabbitmq-username
  rmq-pass: replace-with-rabbitmq-password
