apiVersion: v1
kind: Service
metadata:
  name: opsledger-cache
  labels:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: cache
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
