apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsledger-db
  labels:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opsledger
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opsledger
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: opsledger-db
          image: opsledger/opsledger-db:latest
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opsledger-secret
                  key: db-pass
