apiVersion: v1
kind: Service
metadata:
  name: opsledger-db
  labels:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: database
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
