apiVersion: v1
kind: Service
metadata:
  name: opsledger-queue
  labels:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: queue
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opsledger
    app.kubernetes.io/component: queue
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
