FROM mysql:8.0

ENV MYSQL_DATABASE=accounts
ENV MYSQL_ROOT_HOST=%

COPY src/main/resources/db_backup.sql /docker-entrypoint-initdb.d/01-db_backup.sql

CMD ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]
