#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://opsledger-db:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=${OPSLEDGER_DB_USERNAME}
jdbc.password=${OPSLEDGER_DB_PASSWORD}

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=opsledger-cache
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=opsledger-cache-standby
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=opsledger-queue
rabbitmq.port=5672
rabbitmq.username=${OPSLEDGER_RABBITMQ_USERNAME}
rabbitmq.password=${OPSLEDGER_RABBITMQ_PASSWORD}

#Elasticesearch Configuration
elasticsearch.host =opsledger-search
elasticsearch.port =9300
elasticsearch.cluster=opsledger
elasticsearch.node=opsledgernode
